services:
  # Web application
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      - APP_TITLE=Radio Pronto!
      - NUM_OF_RADIOS_PER_PAGE=21
      - NUM_OF_COUNTRIES_PER_PAGE=30
      - NUM_OF_GENRES_PER_PAGE=30
      - DB_FILE_NAME=/app/data/pronto.db
      - SEARCH_SERVICE_URL=http://search:3001
      - SEARCH_SERVICE_PORT=3001
      - OPENROUTER_API_KEY
      - SESSION_SECRET=your-secret-here
      - NODE_ENV=production
      - SCHEMA_PATH=/app/packages/db/schema.js
    volumes:
      - db-data:/app/data
    expose:
      - "3000"
    restart: unless-stopped
    command:
      ["sh", "-c", "cd /app/apps/web && yarn drizzle-kit migrate && yarn start"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Search service
  search:
    depends_on:
      - web
    build:
      context: .
      dockerfile: apps/search/Dockerfile
    environment:
      - SEARCH_SERVICE_PORT=3001
      - DB_FILE_NAME=/app/data/pronto.db
    volumes:
      - db-data:/app/data
    expose:
      - "3001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # sync:
  #   depends_on:
  #     web:
  #       condition: service_healthy
  #   build:
  #     context: .
  #     dockerfile: apps/sync/Dockerfile
  #   environment:
  #     - DB_FILE_NAME=/app/data/pronto.db
  #   volumes:
  #     - db-data:/app/data
  #   networks:
  #     - pronto-network
  #   command: ["sh", "-c", "node sync.cli.js sync all"]

volumes:
  db-data:
