services:
  # Web application
  web:
    image: ghcr.io/gokceno/pronto-web:latest
    platform: linux/amd64
    environment:
      - APP_TITLE=Radio Pronto!
      - NUM_OF_RADIOS_PER_PAGE=21
      - NUM_OF_COUNTRIES_PER_PAGE=30
      - NUM_OF_GENRES_PER_PAGE=30
      - NODE_ENV=production
      - DB_FILE_NAME=/app/data/pronto.db
      - SCHEMA_PATH=/app/packages/db/schema.js
      - SEARCH_SERVICE_URL=http://search:3001
      - SESSION_SECRET=your-production-secret-here
    volumes:
      - db-data:/app/data
    depends_on:
      - search
  search:
    image: ghcr.io/gokceno/pronto-search:latest
    platform: linux/amd64
    environment:
      - NODE_ENV=production
      - SEARCH_SERVICE_PORT=3001
      - DB_FILE_NAME=/app/data/pronto.db
    volumes:
      - db-data:/app/data
volumes:
  db-data:
