services:
  # Web application
  web:
    image: ghcr.io/gokceno/pronto-web:latest
    environment:
      - APP_TITLE=Radio Pronto!
      - NUM_OF_RADIOS_PER_PAGE=21
      - NUM_OF_COUNTRIES_PER_PAGE=30
      - NUM_OF_GENRES_PER_PAGE=30
      - NODE_ENV=production
      - DB_FILE_NAME=/app/data/pronto.db
      - SCHEMA_PATH=/app/packages/db/schema.js
      - SEARCH_SERVICE_URL=http://search:3001
      - SEARCH_SERVICE_PORT=3001
      - SESSION_SECRET=your-production-secret-here
    volumes:
      - db-data:/app/data
    command: >
      sh -c "
        cd /app/apps/web &&
        echo 'Initializing database...' &&
        yarn drizzle-kit migrate &&
        echo 'Database initialization completed!' &&
        echo 'Starting web application...' &&
        yarn start
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      - search

  # Search service
  search:
    image: ghcr.io/gokceno/pronto-search:latest
    environment:
      - NODE_ENV=production
      - SEARCH_SERVICE_PORT=3001
      - DB_FILE_NAME=/app/data/pronto.db
    volumes:
      - db-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  db-data:
