name: Build Images and Push to Registry
on:
  push:
    branches:
      - main
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Build and Push Images
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Web to Registry
        id: build_push_web
        uses: docker/build-push-action@v5
        with:
          build-args: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          context: .
          file: apps/web/Dockerfile
          push: true
          tags: ghcr.io/gokceno/pronto-web:latest

      - name: Build and Push Search to Registry
        id: build_push_search
        uses: docker/build-push-action@v5
        with:
          build-args: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          context: .
          file: apps/search/Dockerfile
          push: true
          tags: ghcr.io/gokceno/pronto-search:latest
