name: Build Images and Push to Registry
on:
  workflow_dispatch:
jobs:
  build_and_push:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    name: Build and Push Images
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Web to Registry
        id: build_push_web
        uses: docker/build-push-action@v5
        with:
          build-args: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          context: .
          file: apps/web/Dockerfile
          push: true
          tags: ghcr.io/brewinteractive/pronto-web:latest
          platforms: linux/amd64, linux/arm64

      - name: Build and Push Search to Registry
        id: build_push_search
        uses: docker/build-push-action@v5
        with:
          build-args: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          context: .
          file: apps/search/Dockerfile
          push: true
          tags: ghcr.io/brewinteractive/pronto-search:latest
          platforms: linux/amd64, linux/arm64
